Aiming with arrows ( + basis for alpha value)
joncatanio/GrannyGauntlet pull request #141
Opened 2017-03-17 20:32 UTC by nurgan

Aiming with arrows works now. 

Created the basis for using alpha values with our materials, if we want to at some point. To actually use it, would need objects with alpha being drawn last, and to be sorted depended on the players z.

2017-03-17 20:32 UTC, nurgan commented on src/CookieActionComponent.cpp
> +    obj->addRotation(xRot, glm::vec3(0.0, 0.0, -1.0));
tbh, I have no idea why I have to rotate around the negative z axis, but it works.

2017-03-21 01:19 UTC, rgarmsen2295 requested changes
All looks good but please add the MatAlpha to the two other core shaders (Toon and CookTorr) so that it still looks good there as well.  Otherwise, code looks great!

2017-03-21 01:19 UTC, rgarmsen2295 commented on resources/phong_frag.glsl
> +	color = shadowFactor * vec4(directionalLightColor, MatAlpha);
Ooo very cool

2017-03-21 01:19 UTC, rgarmsen2295 commented on src/CookieActionComponent.cpp
> +    obj->addRotation(xRot, glm::vec3(0.0, 0.0, -1.0));
kk lol sounds good

2017-03-21 03:35 UTC, joncatanio reviewed
This looks awesome, once you fix the changes that Reed requested go ahead and merge. What do you guys think on changing the yellow color though? Maybe start with white?

2017-03-21 19:12 UTC, nurgan commented
I'll merge it for now, and play with colors later, I wanna get all the PRs merged

2017-03-21 19:12 UTC, merged